### ISSUE TITLE
Run tests on Pull Requests

### ISSUE THREAD

**Issue by quicksketch** [MukurtuCMS/Mukurtu-CMS#611]
Right now tests are run on the `main` and `develop` branches:

```
on:
  push:
    branches:
      - main
      - develop
```

But they're not run on pull requests. Ideally we'd run the tests before we merge things and not afterward.
